<?php
define('SERVICE_LAUNCHER_START', '1000');
define('SERVICE_LISTENER_START', '1001');
define('SERVICE_WORKER_START','1002');
define('SERVICE_CONTROLLER_START', '1003');
define('SERVICE_CONTROLLER_STOP', '1004');
define('SERVICE_CONTROLLER_ACCEPT','1005');